"""stage9_plan_item_unified

Revision ID: 0e1e46211e89
Revises: aa9f3f5528a5
Create Date: 2026-02-28 16:52:57.146110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1e46211e89'
down_revision: Union[str, Sequence[str], None] = 'aa9f3f5528a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_items', sa.Column('catalog_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plan_items', 'catalog_items', ['catalog_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_items', type_='foreignkey')
    op.drop_column('plan_items', 'catalog_item_id')
    # ### end Alembic commands ###
