"""add_engine_columns_and_duration

Revision ID: 8bc8a024017a
Revises: 9b2083642097
Create Date: 2026-02-15 20:47:39.684354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc8a024017a'
down_revision: Union[str, Sequence[str], None] = '9b2083642097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('lugares', sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('user_plans', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('user_plans', sa.Column('generation_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plans', 'generation_version')
    op.drop_column('user_plans', 'generated_at')
    op.drop_column('lugares', 'estimated_duration_minutes')
    op.drop_column('actividades', 'estimated_duration_minutes')
    # ### end Alembic commands ###
