"""create itinerary hierarchy

Revision ID: 9b2083642097
Revises: 
Create Date: 2026-02-15 20:18:59.338670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b2083642097'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('level', sa.Enum('baja', 'media', 'alta', name='activity_intensity'), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('cost_clp', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['user_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lodging_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('cost_clp', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['user_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('cost_clp', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['lugares.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['user_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['user_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'number', name='uq_plan_day_number')
    )
    op.create_index('idx_day_plan_id', 'plan_days', ['plan_id'], unique=False)
    op.create_table('transport_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('origin_name', sa.String(length=120), nullable=False),
    sa.Column('destination_name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.Enum('auto', 'bus', 'avion', 'barco', name='transport_mode'), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cost_clp', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['user_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('created', 'updated', 'deleted', name='log_action'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['user_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_log_timestamp'), 'travel_log', ['timestamp'], unique=False)
    op.create_table('plan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('place', 'activity', 'transport', 'lodging', name='plan_item_type'), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('lodging_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('cost_clp', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(item_type = 'place' AND place_id IS NOT NULL AND activity_id IS NULL AND lodging_id IS NULL AND transport_id IS NULL) OR (item_type = 'activity' AND activity_id IS NOT NULL AND place_id IS NULL AND lodging_id IS NULL AND transport_id IS NULL) OR (item_type = 'lodging' AND lodging_id IS NOT NULL AND place_id IS NULL AND activity_id IS NULL AND transport_id IS NULL) OR (item_type = 'transport' AND transport_id IS NOT NULL AND place_id IS NULL AND activity_id IS NULL AND lodging_id IS NULL)", name='check_item_type_fk_consistency'),
    sa.CheckConstraint('end_time > start_time', name='check_times_order'),
    sa.ForeignKeyConstraint(['activity_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['day_id'], ['plan_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lodging_id'], ['hospedajes.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['lugares.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transportes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_day_sort', 'plan_items', ['day_id', 'sort_order'], unique=False)
    op.create_index('idx_item_type', 'plan_items', ['item_type'], unique=False)
    op.drop_table('user_plan_preferencias')
    op.create_foreign_key(None, 'historia_viaje', 'user_plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'plan_actividades', 'user_plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'plan_hospedaje', 'user_plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'plan_transporte', 'user_plans', ['plan_id'], ['id'])
    op.add_column('user_plans', sa.Column('budget_clp', sa.Numeric(precision=12, scale=0), nullable=True))
    op.add_column('user_plans', sa.Column('total_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plans', 'total_days')
    op.drop_column('user_plans', 'budget_clp')
    op.drop_constraint(None, 'plan_transporte', type_='foreignkey')
    op.drop_constraint(None, 'plan_hospedaje', type_='foreignkey')
    op.drop_constraint(None, 'plan_actividades', type_='foreignkey')
    op.drop_constraint(None, 'historia_viaje', type_='foreignkey')
    op.create_table('user_plan_preferencias',
    sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preferencia_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['preferencia_id'], ['preferencias.id'], name=op.f('user_plan_preferencias_preferencia_id_fkey')),
    sa.PrimaryKeyConstraint('plan_id', 'preferencia_id', name=op.f('user_plan_preferencias_pkey'))
    )
    op.drop_index('idx_item_type', table_name='plan_items')
    op.drop_index('idx_day_sort', table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_travel_log_timestamp'), table_name='travel_log')
    op.drop_table('travel_log')
    op.drop_table('transport_segments')
    op.drop_index('idx_day_plan_id', table_name='plan_days')
    op.drop_table('plan_days')
    op.drop_table('place_items')
    op.drop_table('lodging_items')
    op.drop_table('activity_items')
    # ### end Alembic commands ###
