"""add_excel_fields_to_lugar

Revision ID: a6ac0426d58f
Revises: d308554a1bfb
Create Date: 2026-02-16 01:13:28.622334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ac0426d58f'
down_revision: Union[str, Sequence[str], None] = 'd308554a1bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lugares', sa.Column('rango_etario', sa.String(), nullable=True))
    op.add_column('lugares', sa.Column('accesibilidad', sa.Text(), nullable=True))
    op.add_column('lugares', sa.Column('direccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lugares', 'direccion')
    op.drop_column('lugares', 'accesibilidad')
    op.drop_column('lugares', 'rango_etario')
    # ### end Alembic commands ###
