"""stage9_unified_catalog

Revision ID: aa9f3f5528a5
Revises: 346fc4bf9fa7
Create Date: 2026-02-28 16:36:15.345563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa9f3f5528a5'
down_revision: Union[str, Sequence[str], None] = '346fc4bf9fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.Enum('place', 'activity', 'route', 'transport', 'lodging', name='catalog_item_type', create_constraint=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('approx_cost_clp', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['catalog_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_item_active', 'catalog_items', ['is_active'], unique=False)
    op.create_index('idx_catalog_item_category', 'catalog_items', ['category_id'], unique=False)
    op.create_index('idx_catalog_item_type', 'catalog_items', ['item_type'], unique=False)
    op.create_table('item_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=False),
    sa.Column('child_item_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('contains', 'near', 'requires', name='item_relation_type', create_constraint=True), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_item_id'], ['catalog_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_item_id'], ['catalog_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_links')
    op.drop_index('idx_catalog_item_type', table_name='catalog_items')
    op.drop_index('idx_catalog_item_category', table_name='catalog_items')
    op.drop_index('idx_catalog_item_active', table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_table('catalog_categories')
    # ### end Alembic commands ###
