"""add_ciudad_id_to_catalog

Revision ID: d308554a1bfb
Revises: 8bc8a024017a
Create Date: 2026-02-15 20:49:48.565748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd308554a1bfb'
down_revision: Union[str, Sequence[str], None] = '8bc8a024017a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('ciudad_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'actividades', 'ciudades', ['ciudad_id'], ['id'])
    op.add_column('lugares', sa.Column('ciudad_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'lugares', 'ciudades', ['ciudad_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lugares', type_='foreignkey')
    op.drop_column('lugares', 'ciudad_id')
    op.drop_constraint(None, 'actividades', type_='foreignkey')
    op.drop_column('actividades', 'ciudad_id')
    # ### end Alembic commands ###
